In [1]:
import numpy as np

In [7]:
arr = np.arange(0,16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
arr[2:5]

array([2, 3, 4])

In [13]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [15]:
arr[6:]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
arr[2:6] = 111
arr

array([  0,   1, 111, 111, 111, 111,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [31]:
#arr is a pointer for numpy, slice and arr have same addr space
slice = arr[:4]
slice[:] = 1111
slice

array([1111, 1111, 1111, 1111])

In [29]:
arr

array([1111, 1111, 1111, 1111,  111,  111,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [33]:
#copying array
copy_arr = arr.copy()
copy_arr

array([1111, 1111, 1111, 1111,  111,  111,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [35]:
copy_arr[:] = 7
copy_arr

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [37]:
arr

array([1111, 1111, 1111, 1111,  111,  111,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [41]:
#2d arrays
arr_2d = np.array([[2,1,4], [2,5,6], [9,34,12]])
arr_2d


array([[ 2,  1,  4],
       [ 2,  5,  6],
       [ 9, 34, 12]])

In [43]:
arr_2d[2][1]

34

In [45]:
arr_2d[2,1]

34

In [47]:
#Grabbing sub arrays
arr_2d

array([[ 2,  1,  4],
       [ 2,  5,  6],
       [ 9, 34, 12]])

In [49]:
#[5,6]
#[34,12]

arr_2d[1:,1:]

array([[ 5,  6],
       [34, 12]])

In [51]:
#boolean array
arr_2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [53]:
bool_arr = arr_2d > 5
arr_2d[bool_arr]

array([ 6,  9, 34, 12])

In [55]:
arr_2d[ arr_2d < 8 ]

array([2, 1, 4, 2, 5, 6])

In [57]:
#practice
arr = np.arange(50).reshape(5,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [59]:
arr[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [61]:
arr[arr>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [63]:
arr[arr<7]

array([0, 1, 2, 3, 4, 5, 6])

In [73]:
arr[arr < 20]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])